"""add_sources_only

Revision ID: 78fa2a5f8720
Revises: add_crawl_history
Create Date: 2025-12-05 03:20:49.974545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78fa2a5f8720'
down_revision: Union[str, None] = 'add_crawl_history'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('crawl_frequency', sa.String(length=50), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(), nullable=True),
    sa.Column('next_crawl_at', sa.DateTime(), nullable=True),
    sa.Column('total_articles', sa.Integer(), nullable=True),
    sa.Column('last_article_count', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Integer(), nullable=True),
    sa.Column('contact_info', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('crawl_params', sa.JSON(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_domain'), 'sources', ['domain'], unique=False)
    op.create_index(op.f('ix_sources_type'), 'sources', ['type'], unique=False)
    op.create_index(op.f('ix_sources_url'), 'sources', ['url'], unique=True)
    op.drop_constraint('uq_articles_url', 'articles', type_='unique')
    op.drop_index('ix_articles_url', table_name='articles')
    op.create_index(op.f('ix_articles_url'), 'articles', ['url'], unique=True)
    op.alter_column('crawl_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('crawl_history', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index('ix_crawl_history_last_checked', table_name='crawl_history')
    op.drop_index('ix_crawl_history_pending', table_name='crawl_history')
    op.drop_index('ix_crawl_history_status', table_name='crawl_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_crawl_history_status', 'crawl_history', ['status'], unique=False)
    op.create_index('ix_crawl_history_pending', 'crawl_history', ['status', 'domain'], unique=False)
    op.create_index('ix_crawl_history_last_checked', 'crawl_history', ['last_checked_at'], unique=False)
    op.alter_column('crawl_history', 'updated_at',
               existing_type=sa.Float(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('crawl_history', 'created_at',
               existing_type=sa.Float(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_articles_url'), table_name='articles')
    op.create_index('ix_articles_url', 'articles', ['url'], unique=False)
    op.create_unique_constraint('uq_articles_url', 'articles', ['url'])
    op.drop_index(op.f('ix_sources_url'), table_name='sources')
    op.drop_index(op.f('ix_sources_type'), table_name='sources')
    op.drop_index(op.f('ix_sources_domain'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
